// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultHandle>>
abstract class VaultHandle implements RustOpaqueInterface {
  /// Compute health information from the in-memory index only (no file I/O or WAL writes).
  ///
  /// The `#[must_use]` attribute is a Rust best practice indicating that the return value
  /// of this function should not be silently ignored by callers.
  Future<VaultHealthInfo> health();
}

/// Result of a vault defragmentation operation.
class DefragResult {
  /// Number of segments that were physically moved on disk.
  final int segmentsMoved;

  /// Bytes of free-list space reclaimed into contiguous unallocated space.
  final BigInt bytesReclaimed;

  /// Number of scattered free regions before defragmentation.
  final int freeRegionsBefore;

  const DefragResult({
    required this.segmentsMoved,
    required this.bytesReclaimed,
    required this.freeRegionsBefore,
  });

  @override
  int get hashCode =>
      segmentsMoved.hashCode ^
      bytesReclaimed.hashCode ^
      freeRegionsBefore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DefragResult &&
          runtimeType == other.runtimeType &&
          segmentsMoved == other.segmentsMoved &&
          bytesReclaimed == other.bytesReclaimed &&
          freeRegionsBefore == other.freeRegionsBefore;
}

/// Capacity info returned to callers.
class VaultCapacityInfo {
  final BigInt totalBytes;
  final BigInt usedBytes;
  final BigInt freeListBytes;
  final BigInt unallocatedBytes;
  final BigInt segmentCount;

  const VaultCapacityInfo({
    required this.totalBytes,
    required this.usedBytes,
    required this.freeListBytes,
    required this.unallocatedBytes,
    required this.segmentCount,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^
      usedBytes.hashCode ^
      freeListBytes.hashCode ^
      unallocatedBytes.hashCode ^
      segmentCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultCapacityInfo &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          usedBytes == other.usedBytes &&
          freeListBytes == other.freeListBytes &&
          unallocatedBytes == other.unallocatedBytes &&
          segmentCount == other.segmentCount;
}

/// Vault health and diagnostic info returned to callers.
///
/// `#[frb(non_opaque)]` tells the code generator to expose this as a direct Dart class
/// with all these fields accessible, instead of hiding it behind a pointer.
class VaultHealthInfo {
  final BigInt totalBytes;
  final BigInt usedBytes;
  final BigInt freeListBytes;
  final BigInt unallocatedBytes;
  final int segmentCount;
  final int freeRegionCount;
  final BigInt largestFreeBlock;

  /// 0.0 = no fragmentation, 1.0 = all free space is fragmented
  final double fragmentationRatio;

  const VaultHealthInfo({
    required this.totalBytes,
    required this.usedBytes,
    required this.freeListBytes,
    required this.unallocatedBytes,
    required this.segmentCount,
    required this.freeRegionCount,
    required this.largestFreeBlock,
    required this.fragmentationRatio,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^
      usedBytes.hashCode ^
      freeListBytes.hashCode ^
      unallocatedBytes.hashCode ^
      segmentCount.hashCode ^
      freeRegionCount.hashCode ^
      largestFreeBlock.hashCode ^
      fragmentationRatio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultHealthInfo &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          usedBytes == other.usedBytes &&
          freeListBytes == other.freeListBytes &&
          unallocatedBytes == other.unallocatedBytes &&
          segmentCount == other.segmentCount &&
          freeRegionCount == other.freeRegionCount &&
          largestFreeBlock == other.largestFreeBlock &&
          fragmentationRatio == other.fragmentationRatio;
}
