// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/encryption.dart';
import 'api/encryption/aes_gcm.dart';
import 'api/encryption/chacha20.dart';
import 'api/encryption/noop.dart';
import 'api/hashing.dart';
import 'api/hashing/argon2.dart';
import 'api/kdf/hkdf.dart';
import 'core/error.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1451637143;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_m_security',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiEncryptionNoopNoopEncryptionAlgorithmId({
    required NoopEncryption that,
  });

  Future<Uint8List> crateApiEncryptionNoopNoopEncryptionDecrypt({
    required NoopEncryption that,
    required List<int> ciphertext,
    required List<int> aad,
  });

  Future<Uint8List> crateApiEncryptionNoopNoopEncryptionEncrypt({
    required NoopEncryption that,
    required List<int> plaintext,
    required List<int> aad,
  });

  Future<String> crateApiHashingArgon2Argon2IdHash({
    required String password,
    required Argon2Preset preset,
  });

  Future<String> crateApiHashingArgon2Argon2IdHashWithSalt({
    required String password,
    required String salt,
    required Argon2Preset preset,
  });

  Future<void> crateApiHashingArgon2Argon2IdVerify({
    required String phcHash,
    required String password,
  });

  Future<Uint8List> crateApiHashingBlake3Hash({required List<int> data});

  Future<CipherHandle> crateApiEncryptionCreateAes256Gcm({
    required List<int> key,
  });

  Future<HasherHandle> crateApiHashingCreateBlake3();

  Future<CipherHandle> crateApiEncryptionCreateChacha20Poly1305({
    required List<int> key,
  });

  Future<CipherHandle> crateApiEncryptionCreateNoopEncryption();

  Future<HasherHandle> crateApiHashingCreateSha3();

  Future<Uint8List> crateApiEncryptionDecrypt({
    required CipherHandle cipher,
    required List<int> ciphertext,
    required List<int> aad,
  });

  Future<Uint8List> crateApiEncryptionEncrypt({
    required CipherHandle cipher,
    required List<int> plaintext,
    required List<int> aad,
  });

  Future<String> crateApiEncryptionEncryptionAlgorithmId({
    required CipherHandle cipher,
  });

  Future<Uint8List> crateApiEncryptionGenerateAes256GcmKey();

  Future<Uint8List> crateApiEncryptionAesGcmGenerateAesKey();

  Future<Uint8List> crateApiEncryptionGenerateChacha20Poly1305Key();

  Future<Uint8List> crateApiEncryptionChacha20GenerateChachaKey();

  Future<String> crateApiHashingHasherAlgorithmId({
    required HasherHandle handle,
  });

  Future<Uint8List> crateApiHashingHasherFinalize({
    required HasherHandle handle,
  });

  Future<void> crateApiHashingHasherReset({required HasherHandle handle});

  Future<void> crateApiHashingHasherUpdate({
    required HasherHandle handle,
    required List<int> data,
  });

  Uint8List crateApiKdfHkdfHkdfDerive({
    required List<int> ikm,
    Uint8List? salt,
    required List<int> info,
    required BigInt outputLen,
  });

  Future<Uint8List> crateApiKdfHkdfHkdfExpand({
    required List<int> prk,
    required List<int> info,
    required BigInt outputLen,
  });

  Uint8List crateApiKdfHkdfHkdfExtract({
    required List<int> ikm,
    Uint8List? salt,
  });

  Future<Uint8List> crateApiHashingSha3Hash({required List<int> data});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CipherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CipherHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CipherHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HasherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HasherHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_HasherHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NoopEncryption;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NoopEncryption;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NoopEncryptionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiEncryptionNoopNoopEncryptionAlgorithmId({
    required NoopEncryption that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEncryptionNoopNoopEncryptionAlgorithmIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionNoopNoopEncryptionAlgorithmIdConstMeta =>
      const TaskConstMeta(
        debugName: "NoopEncryption_algorithm_id",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiEncryptionNoopNoopEncryptionDecrypt({
    required NoopEncryption that,
    required List<int> ciphertext,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionNoopNoopEncryptionDecryptConstMeta,
        argValues: [that, ciphertext, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionNoopNoopEncryptionDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "NoopEncryption_decrypt",
        argNames: ["that", "ciphertext", "aad"],
      );

  @override
  Future<Uint8List> crateApiEncryptionNoopNoopEncryptionEncrypt({
    required NoopEncryption that,
    required List<int> plaintext,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionNoopNoopEncryptionEncryptConstMeta,
        argValues: [that, plaintext, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionNoopNoopEncryptionEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "NoopEncryption_encrypt",
        argNames: ["that", "plaintext", "aad"],
      );

  @override
  Future<String> crateApiHashingArgon2Argon2IdHash({
    required String password,
    required Argon2Preset preset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_argon_2_preset(preset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingArgon2Argon2IdHashConstMeta,
        argValues: [password, preset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingArgon2Argon2IdHashConstMeta =>
      const TaskConstMeta(
        debugName: "argon2id_hash",
        argNames: ["password", "preset"],
      );

  @override
  Future<String> crateApiHashingArgon2Argon2IdHashWithSalt({
    required String password,
    required String salt,
    required Argon2Preset preset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_String(salt, serializer);
          sse_encode_argon_2_preset(preset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingArgon2Argon2IdHashWithSaltConstMeta,
        argValues: [password, salt, preset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingArgon2Argon2IdHashWithSaltConstMeta =>
      const TaskConstMeta(
        debugName: "argon2id_hash_with_salt",
        argNames: ["password", "salt", "preset"],
      );

  @override
  Future<void> crateApiHashingArgon2Argon2IdVerify({
    required String phcHash,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phcHash, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingArgon2Argon2IdVerifyConstMeta,
        argValues: [phcHash, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingArgon2Argon2IdVerifyConstMeta =>
      const TaskConstMeta(
        debugName: "argon2id_verify",
        argNames: ["phcHash", "password"],
      );

  @override
  Future<Uint8List> crateApiHashingBlake3Hash({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHashingBlake3HashConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingBlake3HashConstMeta =>
      const TaskConstMeta(debugName: "blake3_hash", argNames: ["data"]);

  @override
  Future<CipherHandle> crateApiEncryptionCreateAes256Gcm({
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionCreateAes256GcmConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionCreateAes256GcmConstMeta =>
      const TaskConstMeta(debugName: "create_aes256_gcm", argNames: ["key"]);

  @override
  Future<HasherHandle> crateApiHashingCreateBlake3() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHashingCreateBlake3ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingCreateBlake3ConstMeta =>
      const TaskConstMeta(debugName: "create_blake3", argNames: []);

  @override
  Future<CipherHandle> crateApiEncryptionCreateChacha20Poly1305({
    required List<int> key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionCreateChacha20Poly1305ConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionCreateChacha20Poly1305ConstMeta =>
      const TaskConstMeta(
        debugName: "create_chacha20_poly1305",
        argNames: ["key"],
      );

  @override
  Future<CipherHandle> crateApiEncryptionCreateNoopEncryption() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEncryptionCreateNoopEncryptionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionCreateNoopEncryptionConstMeta =>
      const TaskConstMeta(debugName: "create_noop_encryption", argNames: []);

  @override
  Future<HasherHandle> crateApiHashingCreateSha3() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHashingCreateSha3ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingCreateSha3ConstMeta =>
      const TaskConstMeta(debugName: "create_sha3", argNames: []);

  @override
  Future<Uint8List> crateApiEncryptionDecrypt({
    required CipherHandle cipher,
    required List<int> ciphertext,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
            cipher,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionDecryptConstMeta,
        argValues: [cipher, ciphertext, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionDecryptConstMeta => const TaskConstMeta(
    debugName: "decrypt",
    argNames: ["cipher", "ciphertext", "aad"],
  );

  @override
  Future<Uint8List> crateApiEncryptionEncrypt({
    required CipherHandle cipher,
    required List<int> plaintext,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
            cipher,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionEncryptConstMeta,
        argValues: [cipher, plaintext, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionEncryptConstMeta => const TaskConstMeta(
    debugName: "encrypt",
    argNames: ["cipher", "plaintext", "aad"],
  );

  @override
  Future<String> crateApiEncryptionEncryptionAlgorithmId({
    required CipherHandle cipher,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
            cipher,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEncryptionEncryptionAlgorithmIdConstMeta,
        argValues: [cipher],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionEncryptionAlgorithmIdConstMeta =>
      const TaskConstMeta(
        debugName: "encryption_algorithm_id",
        argNames: ["cipher"],
      );

  @override
  Future<Uint8List> crateApiEncryptionGenerateAes256GcmKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionGenerateAes256GcmKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionGenerateAes256GcmKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_aes256_gcm_key", argNames: []);

  @override
  Future<Uint8List> crateApiEncryptionAesGcmGenerateAesKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionAesGcmGenerateAesKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionAesGcmGenerateAesKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_aes_key", argNames: []);

  @override
  Future<Uint8List> crateApiEncryptionGenerateChacha20Poly1305Key() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionGenerateChacha20Poly1305KeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionGenerateChacha20Poly1305KeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_chacha20_poly1305_key",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiEncryptionChacha20GenerateChachaKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiEncryptionChacha20GenerateChachaKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptionChacha20GenerateChachaKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_chacha_key", argNames: []);

  @override
  Future<String> crateApiHashingHasherAlgorithmId({
    required HasherHandle handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingHasherAlgorithmIdConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingHasherAlgorithmIdConstMeta =>
      const TaskConstMeta(
        debugName: "hasher_algorithm_id",
        argNames: ["handle"],
      );

  @override
  Future<Uint8List> crateApiHashingHasherFinalize({
    required HasherHandle handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingHasherFinalizeConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingHasherFinalizeConstMeta =>
      const TaskConstMeta(debugName: "hasher_finalize", argNames: ["handle"]);

  @override
  Future<void> crateApiHashingHasherReset({required HasherHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingHasherResetConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingHasherResetConstMeta =>
      const TaskConstMeta(debugName: "hasher_reset", argNames: ["handle"]);

  @override
  Future<void> crateApiHashingHasherUpdate({
    required HasherHandle handle,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
            handle,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiHashingHasherUpdateConstMeta,
        argValues: [handle, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingHasherUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "hasher_update",
        argNames: ["handle", "data"],
      );

  @override
  Uint8List crateApiKdfHkdfHkdfDerive({
    required List<int> ikm,
    Uint8List? salt,
    required List<int> info,
    required BigInt outputLen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ikm, serializer);
          sse_encode_opt_list_prim_u_8_strict(salt, serializer);
          sse_encode_list_prim_u_8_loose(info, serializer);
          sse_encode_usize(outputLen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiKdfHkdfHkdfDeriveConstMeta,
        argValues: [ikm, salt, info, outputLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKdfHkdfHkdfDeriveConstMeta => const TaskConstMeta(
    debugName: "hkdf_derive",
    argNames: ["ikm", "salt", "info", "outputLen"],
  );

  @override
  Future<Uint8List> crateApiKdfHkdfHkdfExpand({
    required List<int> prk,
    required List<int> info,
    required BigInt outputLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(prk, serializer);
          sse_encode_list_prim_u_8_loose(info, serializer);
          sse_encode_usize(outputLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiKdfHkdfHkdfExpandConstMeta,
        argValues: [prk, info, outputLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKdfHkdfHkdfExpandConstMeta => const TaskConstMeta(
    debugName: "hkdf_expand",
    argNames: ["prk", "info", "outputLen"],
  );

  @override
  Uint8List crateApiKdfHkdfHkdfExtract({
    required List<int> ikm,
    Uint8List? salt,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ikm, serializer);
          sse_encode_opt_list_prim_u_8_strict(salt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateApiKdfHkdfHkdfExtractConstMeta,
        argValues: [ikm, salt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKdfHkdfHkdfExtractConstMeta =>
      const TaskConstMeta(debugName: "hkdf_extract", argNames: ["ikm", "salt"]);

  @override
  Future<Uint8List> crateApiHashingSha3Hash({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHashingSha3HashConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHashingSha3HashConstMeta =>
      const TaskConstMeta(debugName: "sha3_hash", argNames: ["data"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CipherHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CipherHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HasherHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HasherHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NoopEncryption => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NoopEncryption => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption;

  @protected
  CipherHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CipherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HasherHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HasherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NoopEncryption
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CipherHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CipherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HasherHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HasherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NoopEncryption
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CipherHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CipherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HasherHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HasherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NoopEncryption
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Argon2Preset dco_decode_argon_2_preset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Argon2Preset.values[raw as int];
  }

  @protected
  CryptoError dco_decode_crypto_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CryptoError_InvalidKeyLength(
          expected: dco_decode_usize(raw[1]),
          actual: dco_decode_usize(raw[2]),
        );
      case 1:
        return CryptoError_InvalidNonce();
      case 2:
        return CryptoError_EncryptionFailed(dco_decode_String(raw[1]));
      case 3:
        return CryptoError_DecryptionFailed();
      case 4:
        return CryptoError_HashingFailed(dco_decode_String(raw[1]));
      case 5:
        return CryptoError_KdfFailed(dco_decode_String(raw[1]));
      case 6:
        return CryptoError_IoError(dco_decode_String(raw[1]));
      case 7:
        return CryptoError_InvalidParameter(dco_decode_String(raw[1]));
      case 8:
        return CryptoError_AuthenticationFailed();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CipherHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CipherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HasherHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HasherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NoopEncryption
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CipherHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CipherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HasherHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HasherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NoopEncryption
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CipherHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CipherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HasherHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HasherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NoopEncryption
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NoopEncryptionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Argon2Preset sse_decode_argon_2_preset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Argon2Preset.values[inner];
  }

  @protected
  CryptoError sse_decode_crypto_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_expected = sse_decode_usize(deserializer);
        var var_actual = sse_decode_usize(deserializer);
        return CryptoError_InvalidKeyLength(
          expected: var_expected,
          actual: var_actual,
        );
      case 1:
        return CryptoError_InvalidNonce();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return CryptoError_EncryptionFailed(var_field0);
      case 3:
        return CryptoError_DecryptionFailed();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return CryptoError_HashingFailed(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return CryptoError_KdfFailed(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return CryptoError_IoError(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return CryptoError_InvalidParameter(var_field0);
      case 8:
        return CryptoError_AuthenticationFailed();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    CipherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CipherHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    HasherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HasherHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    NoopEncryption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NoopEncryptionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    CipherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CipherHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    HasherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HasherHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    NoopEncryption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NoopEncryptionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCipherHandle(
    CipherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CipherHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHasherHandle(
    HasherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HasherHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoopEncryption(
    NoopEncryption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NoopEncryptionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_argon_2_preset(Argon2Preset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_crypto_error(CryptoError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CryptoError_InvalidKeyLength(
        expected: final expected,
        actual: final actual,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_usize(expected, serializer);
        sse_encode_usize(actual, serializer);
      case CryptoError_InvalidNonce():
        sse_encode_i_32(1, serializer);
      case CryptoError_EncryptionFailed(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case CryptoError_DecryptionFailed():
        sse_encode_i_32(3, serializer);
      case CryptoError_HashingFailed(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case CryptoError_KdfFailed(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case CryptoError_IoError(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case CryptoError_InvalidParameter(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case CryptoError_AuthenticationFailed():
        sse_encode_i_32(8, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class CipherHandleImpl extends RustOpaque implements CipherHandle {
  // Not to be used by end users
  CipherHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CipherHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CipherHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CipherHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CipherHandlePtr,
  );
}

@sealed
class HasherHandleImpl extends RustOpaque implements HasherHandle {
  // Not to be used by end users
  HasherHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HasherHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HasherHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HasherHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HasherHandlePtr,
  );
}

@sealed
class NoopEncryptionImpl extends RustOpaque implements NoopEncryption {
  // Not to be used by end users
  NoopEncryptionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NoopEncryptionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NoopEncryption,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NoopEncryption,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NoopEncryptionPtr,
  );

  Future<void> algorithmId() => RustLib.instance.api
      .crateApiEncryptionNoopNoopEncryptionAlgorithmId(that: this);

  Future<Uint8List> decrypt({
    required List<int> ciphertext,
    required List<int> aad,
  }) => RustLib.instance.api.crateApiEncryptionNoopNoopEncryptionDecrypt(
    that: this,
    ciphertext: ciphertext,
    aad: aad,
  );

  Future<Uint8List> encrypt({
    required List<int> plaintext,
    required List<int> aad,
  }) => RustLib.instance.api.crateApiEncryptionNoopNoopEncryptionEncrypt(
    that: this,
    plaintext: plaintext,
    aad: aad,
  );
}
