// Assemble the exact publish payload and record what it contains.
//
//   dart run tool/publication.dart --out <dir>
//
// The inclusion set comes from `flutter pub publish --dry-run`, which is the
// only thing that knows what pub would upload. Every entry has to be a tracked
// file, so the payload is a function of the revision rather than of whatever a
// local build left behind. The output is a directory of byte-identical copies,
// a sorted manifest, a normalized archive and a JSON report of the digests.
//
// One limit worth stating: pub's printed tree omits every dot-prefixed entry,
// so the parse below cannot see one. This pub does not publish them either,
// which was checked by writing 32 MiB of random bytes into `ios/Assets/.gitkeep`
// and into `rust_builder/android/.gradle/8.9/gc.properties`, both tracked, and
// into an untracked `.probe/blob.bin` and `lib/.probe/blob.bin`, and watching
// the reported archive size hold at 620 KB each time while the same bytes in a
// non-dot directory took it to 46 MB. A directory whose only children are
// dot-prefixed still prints, with nothing under it. That is a measurement, not
// something this program re-proves on every run.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

const String _usage = 'usage: dart run tool/publication.dart --out <dir>';

/// Dry-run complaints that are not payload defects.
///
/// A dirty worktree is what working on the package looks like. The bridge
/// constraint is deliberately a single version: the committed bindings are
/// generated by one exact bridge release and refuse to initialise against any
/// other, so pub's advice to widen it would ship a package that cannot start.
///
/// That second entry matches on the dependency name, not its version, so a
/// bridge bump keeps it tolerated. It goes stale only if pub rewords the
/// complaint or the dependency is renamed, and either way the run fails rather
/// than waving something through.
const List<String> _toleratedComplaints = [
  'modified in git',
  '"flutter_rust_bridge" should allow more than one version',
];

Future<void> main(List<String> args) async {
  final out = _parseArgs(args);
  final repoRoot = Directory.current.absolute.path;

  final dryRun = await _dryRun(repoRoot);
  final inclusion = parseInclusionSet(dryRun);
  if (inclusion.isEmpty) {
    _fail('the dry run reported no files; its output was:\n$dryRun');
  }

  // A file git ignores is one this machine happens to have: the last local
  // test run's output, a Podfile.lock from a pod install. Those are what made
  // the payload vary by machine, so they end the run.
  final ignored = await _ignoredFiles(repoRoot, inclusion);
  if (ignored.isNotEmpty) {
    _fail(
      'the publish payload would carry ${ignored.length} git-ignored file(s), '
      'so it is not a function of the revision:\n'
      '${ignored.map((path) => '  $path').join('\n')}',
    );
  }

  // Not yet tracked is a different thing: it is what an unfinished change
  // looks like, and CI checks out a tree that has none. Worth saying, not
  // worth stopping for.
  final tracked = await _trackedFiles(repoRoot);
  final uncommitted = inclusion
      .where((path) => !tracked.contains(path))
      .toList();
  for (final path in uncommitted) {
    stderr.writeln('publication: not committed yet: $path');
  }

  final payloadDir = Directory(out);
  if (payloadDir.existsSync()) payloadDir.deleteSync(recursive: true);
  payloadDir.createSync(recursive: true);

  final entries = <_Entry>[];
  for (final path in inclusion) {
    final source = File('$repoRoot/$path');
    final bytes = source.readAsBytesSync();
    final target = File('${payloadDir.path}/$path');
    target.parent.createSync(recursive: true);
    target.writeAsBytesSync(bytes);

    // pub keeps the executable bit, and `cargokit/build_pod.sh` needs it to run
    // at all, so a payload that flattened every mode to 0644 would not build on
    // Apple. Nothing here needs a finer mode than executable or not.
    final executable = source.statSync().mode & 0x49 != 0;
    final mode = executable ? 493 : 420; // 0755 or 0644
    if (executable) await _capture('chmod', ['0755', target.path], repoRoot);

    final digest = sha256.convert(bytes).toString();
    if (sha256.convert(target.readAsBytesSync()).toString() != digest) {
      _fail('the copy of $path does not match the source');
    }
    entries.add(_Entry(path, bytes.length, mode, digest));
  }

  final manifest = File('$out.manifest.txt');
  manifest.writeAsStringSync(
    '${entries.map((e) => '${e.digest}  ${e.modeString}  ${e.size}  ${e.path}').join('\n')}\n',
  );
  final payloadDigest = sha256.convert(manifest.readAsBytesSync()).toString();

  final archive = File('$out.tar');
  archive.writeAsBytesSync(_buildTar(entries, payloadDir.path));
  final archiveDigest = sha256.convert(archive.readAsBytesSync()).toString();
  await _verifyArchive(archive, entries);

  // A clean CI checkout has reported a dirty worktree while pub reported no
  // modified file, so something exists on the runner that pub cannot see.
  // Either an untracked path, or a tracked one `.pubignore` keeps out of the
  // payload, since pub's own check only looks at files it would publish.
  // Naming it beats inferring it.
  //
  // NOTE: on a public repository the job log is world-readable, so this prints
  // paths somewhere more visible than the retained report. It is a path list
  // from a CI checkout, which holds nothing private, but do not widen it to
  // file contents.
  final porcelain = await _capture('git', ['status', '--porcelain'], repoRoot);
  if (porcelain.isNotEmpty) {
    stderr.writeln('publication: worktree is not clean:');
    for (final line in porcelain.split('\n')) {
      stderr.writeln('  $line');
    }
  }

  final report = <String, Object?>{
    'revision': await _capture('git', ['rev-parse', 'HEAD'], repoRoot),
    'flutter': (await _capture(
      'flutter',
      ['--version'],
      repoRoot,
    )).split('\n').first,
    'dart': await _capture('dart', ['--version'], repoRoot),
    'rustc': await _capture('rustc', ['--version'], repoRoot),
    // The revision above names a commit; these two say how far the bytes that
    // were hashed have drifted from it. The paths themselves stay on stderr so
    // this stays a fixed-shape record rather than growing a list whose length
    // depends on the machine.
    'worktree_clean': porcelain.isEmpty,
    'file_count': entries.length,
    'uncommitted_count': uncommitted.length,
    'total_bytes': entries.fold<int>(0, (sum, e) => sum + e.size),
    'payload_digest': payloadDigest,
    'archive_digest': archiveDigest,
    'payload_dir': payloadDir.path,
    'manifest_path': manifest.path,
    'archive_path': archive.path,
  };
  final reportFile = File('$out.report.json');
  reportFile.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(report)}\n',
  );

  stdout
    ..writeln('payload files   ${entries.length}')
    ..writeln('payload digest  $payloadDigest')
    ..writeln('archive digest  $archiveDigest')
    ..writeln('payload dir     ${payloadDir.path}')
    ..writeln('report          ${reportFile.path}');
}

class _Entry {
  const _Entry(this.path, this.size, this.mode, this.digest);

  final String path;
  final int size;
  final int mode;
  final String digest;

  String get modeString => mode.toRadixString(8).padLeft(4, '0');
}

String _parseArgs(List<String> args) {
  String? out;
  for (var i = 0; i < args.length; i++) {
    if (args[i] == '--out' && i + 1 < args.length) {
      out = args[++i];
    } else {
      _fail('unrecognized argument ${args[i]}\n$_usage');
    }
  }
  if (out == null) _fail(_usage);
  // A trailing slash would turn the sibling files into dotfiles.
  return File(out.replaceFirst(RegExp(r'/+$'), '')).absolute.path;
}

/// Run the dry run and refuse anything it complains about except a dirty
/// worktree.
///
/// pub prints hints, warnings and errors with the same `* ` prefix but only
/// leaves the exit code nonzero for the last two, so a zero exit is taken at
/// its word. On a nonzero exit each complaint is read against
/// [_toleratedComplaints], because 65 covers both a tracked file that a
/// `.gitignore` hides, which is a payload defect, and things that are the
/// intended state of the package.
Future<String> _dryRun(String repoRoot) async {
  final result = await Process.run(
    'flutter',
    ['pub', 'publish', '--dry-run'],
    workingDirectory: repoRoot,
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  final output = '${result.stdout}${result.stderr}';
  if (result.exitCode == 0) return output;

  final complaints = const LineSplitter()
      .convert(output)
      .where((line) => line.startsWith('* '))
      .toList();
  final unexpected = complaints
      .where((line) => !_toleratedComplaints.any(line.contains))
      .toList();

  if (unexpected.isNotEmpty || complaints.isEmpty) {
    _fail(
      'flutter pub publish --dry-run exited ${result.exitCode}:\n$output',
    );
  }
  for (final complaint in complaints) {
    stderr.writeln('publication: tolerated: $complaint');
  }
  return output;
}

/// Turn pub's printed tree into the sorted list of files it would upload.
///
/// Lines look like `│   ├── frb_generated.rs (202 KB)`. A trailing size marks a
/// file; without one the entry is a directory, and a directory can be a leaf
/// when everything below it is dot-prefixed and therefore not printed.
List<String> parseInclusionSet(String dryRun) {
  final lines = const LineSplitter().convert(dryRun);
  final start = lines.indexWhere((line) => line.startsWith('Publishing '));
  if (start < 0) return const [];
  var end = lines.indexWhere(
    (line) => line.startsWith('Total compressed archive size'),
    start,
  );
  if (end < 0) end = lines.length;

  final entry = RegExp(r'^((?:(?:│   )|(?:    ))*)(?:├── |└── )(.*)$');
  final size = RegExp(r'^(.*) \((?:<1 [KMG]?B|\d+(?:\.\d+)? ?[KMG]?B)\)$');

  final stack = <String>[];
  final files = <String>[];
  for (final line in lines.getRange(start + 1, end)) {
    if (line.trim().isEmpty) continue;
    final match = entry.firstMatch(line);
    if (match == null) {
      _fail('could not parse a line of the dry-run tree: $line');
    }
    final depth = match.group(1)!.length ~/ 4;
    var name = match.group(2)!;
    final sized = size.firstMatch(name);
    if (sized != null) name = sized.group(1)!;

    stack.removeRange(depth.clamp(0, stack.length), stack.length);
    stack.add(name);
    if (sized != null) files.add(stack.join('/'));
  }
  files.sort();
  return files;
}

/// The subset of [paths] that git's ignore rules exclude.
///
/// `--no-index` is what makes this useful: without it a tracked file is never
/// reported, and a tracked file that a `.gitignore` also names is exactly the
/// case worth catching.
Future<List<String>> _ignoredFiles(String repoRoot, List<String> paths) async {
  final process = await Process.start('git', [
    'check-ignore',
    '--no-index',
    '--stdin',
  ], workingDirectory: repoRoot);

  // Both pipes are being read before anything is written, so a long list of
  // matches cannot fill git's stdout buffer and stall the write below.
  final stdoutDone = process.stdout.transform(utf8.decoder).join();
  final stderrDone = process.stderr.transform(utf8.decoder).join();
  process.stdin.write(paths.join('\n'));
  await process.stdin.close();

  final out = await stdoutDone;
  final err = await stderrDone;
  final code = await process.exitCode;
  // 0 means some path matched, 1 means none did. Anything else is a failure.
  if (code != 0 && code != 1) {
    _fail('git check-ignore exited $code: $err');
  }
  return const LineSplitter()
      .convert(out)
      .where((line) => line.isNotEmpty)
      .toList();
}

Future<Set<String>> _trackedFiles(String repoRoot) async {
  final result = await Process.run(
    'git',
    ['ls-files', '-z'],
    workingDirectory: repoRoot,
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  if (result.exitCode != 0) _fail('git ls-files failed: ${result.stderr}');
  return (result.stdout as String)
      .split('\u0000')
      .where((path) => path.isNotEmpty)
      .toSet();
}

/// A minimal deterministic ustar writer.
///
/// Writing it here rather than shelling out to `tar` is what makes the archive
/// digest comparable between a developer's machine and CI: GNU tar and bsdtar
/// disagree on padding and on which optional fields they fill, so the same
/// payload hashes differently under each. Every variable field is pinned here:
/// uid and gid 0, empty owner names, mtime 0, entries in manifest order. Mode
/// is the one thing carried over from the source, and only as executable or
/// not.
List<int> _buildTar(List<_Entry> entries, String payloadDir) {
  final out = BytesBuilder();
  for (final entry in entries) {
    final bytes = File('$payloadDir/${entry.path}').readAsBytesSync();
    out.add(tarHeader(entry.path, bytes.length, entry.mode));
    out.add(bytes);
    out.add(List<int>.filled((512 - bytes.length % 512) % 512, 0));
  }
  out.add(List<int>.filled(1024, 0));
  return out.takeBytes();
}

/// One 512-byte ustar header. Exposed so the prefix split, which no path in
/// this package is long enough to reach, still has a test.
List<int> tarHeader(String path, int size, int mode) {
  var name = path;
  var prefix = '';
  if (utf8.encode(name).length > 100) {
    final cut = name.lastIndexOf('/');
    if (cut <= 0) _fail('path too long for ustar: $path');
    prefix = name.substring(0, cut);
    name = name.substring(cut + 1);
    if (utf8.encode(name).length > 100 || utf8.encode(prefix).length > 155) {
      _fail('path too long for ustar: $path');
    }
  }

  final header = List<int>.filled(512, 0);
  void put(int offset, List<int> value) =>
      header.setRange(offset, offset + value.length, value);

  // Octal, left-padded with zeros, one byte short of the field so the trailing
  // NUL terminates it.
  String octal(int value, int width) =>
      value.toRadixString(8).padLeft(width - 1, '0');

  // Plain ustar has no room for a larger size, and silently writing over the
  // next field would produce an archive that extracts wrong.
  if (size >= 1 << 33) _fail('file too large for ustar: $path');

  put(0, utf8.encode(name));
  put(100, utf8.encode(octal(mode, 8)));
  put(108, utf8.encode(octal(0, 8))); // uid
  put(116, utf8.encode(octal(0, 8))); // gid
  put(124, utf8.encode(octal(size, 12)));
  put(136, utf8.encode(octal(0, 12))); // mtime
  put(148, utf8.encode('        ')); // the checksum counts as spaces
  header[156] = 0x30; // typeflag '0', a regular file
  put(257, utf8.encode('ustar'));
  put(263, utf8.encode('00'));
  put(345, utf8.encode(prefix));

  final checksum = header.fold<int>(0, (sum, byte) => sum + byte);
  put(148, utf8.encode(octal(checksum, 7)));
  header[154] = 0; // six octal digits, then NUL and space
  header[155] = 0x20;
  return header;
}

/// Extract the archive with the system `tar` and compare it back to the
/// manifest, so a bug in the writer above fails here instead of shipping a
/// decorative artifact.
Future<void> _verifyArchive(File archive, List<_Entry> entries) async {
  final scratch = Directory.systemTemp.createTempSync('m_security_tar');
  // `_fail` calls `exit`, which does not unwind, so the scratch copy has to go
  // before the message rather than in a `finally`.
  Never fail(String message) {
    scratch.deleteSync(recursive: true);
    _fail(message);
  }

  final result = await Process.run(
    'tar',
    ['-xf', archive.path, '-C', scratch.path],
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  if (result.exitCode != 0) {
    fail('tar could not read the archive: ${result.stderr}');
  }
  for (final entry in entries) {
    final extracted = File('${scratch.path}/${entry.path}');
    if (!extracted.existsSync()) fail('the archive is missing ${entry.path}');
    if (sha256.convert(extracted.readAsBytesSync()).toString() !=
        entry.digest) {
      fail('the archive holds a different ${entry.path}');
    }
    if (extracted.statSync().mode & 0x1FF != entry.mode) {
      fail('the archive holds ${entry.path} with the wrong mode');
    }
  }
  final count = scratch.listSync(recursive: true).whereType<File>().length;
  if (count != entries.length) {
    fail('the archive holds $count files, the manifest ${entries.length}');
  }
  scratch.deleteSync(recursive: true);
}

Future<String> _capture(
  String executable,
  List<String> args,
  String workingDirectory,
) async {
  final result = await Process.run(
    executable,
    args,
    workingDirectory: workingDirectory,
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  if (result.exitCode != 0) {
    _fail('$executable ${args.join(' ')} exited ${result.exitCode}');
  }
  return (result.stdout as String).trim();
}

Never _fail(String message) {
  stderr.writeln('publication: $message');
  exit(1);
}
