// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A buffer that securely zeroes its contents when dropped.
///
/// Use this for all key material to ensure secrets don't linger in memory.
class SecretBuffer {
  final Uint8List inner;

  const SecretBuffer({required this.inner});

  @override
  int get hashCode => inner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecretBuffer &&
          runtimeType == other.runtimeType &&
          inner == other.inner;
}
