// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../core/error.dart';
import '../../core/traits.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a random 32-byte AES-256 key.
Future<Uint8List> generateAesKey() =>
    RustLib.instance.api.crateApiEncryptionAesGcmGenerateAesKey();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Aes256GcmCipher>>
abstract class Aes256GcmCipher implements RustOpaqueInterface, Encryption {
  Future<void> algorithmId();

  Future<Uint8List> decrypt({
    required List<int> ciphertext,
    required List<int> aad,
  });

  Future<Uint8List> encrypt({
    required List<int> plaintext,
    required List<int> aad,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Aes256GcmCipher> newInstance({required List<int> key}) =>
      RustLib.instance.api.crateApiEncryptionAesGcmAes256GcmCipherNew(key: key);
}
