// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../core/error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A no-op cipher that returns data unchanged.
/// Used to validate FRB opaque handle pattern works.
class NoopEncryption {
  const NoopEncryption();

  Future<void> algorithmId() => RustLib.instance.api
      .crateApiEncryptionNoopNoopEncryptionAlgorithmId(that: this);

  Future<Uint8List> decrypt({
    required List<int> ciphertext,
    required List<int> aad,
  }) => RustLib.instance.api.crateApiEncryptionNoopNoopEncryptionDecrypt(
    that: this,
    ciphertext: ciphertext,
    aad: aad,
  );

  Future<Uint8List> encrypt({
    required List<int> plaintext,
    required List<int> aad,
  }) => RustLib.instance.api.crateApiEncryptionNoopNoopEncryptionEncrypt(
    that: this,
    plaintext: plaintext,
    aad: aad,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoopEncryption && runtimeType == other.runtimeType;
}
