// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

abstract class Encyprtion {
  /// Encrypt a single chunk of data.
  Future<Uint8List> encrypt({required List<int> chunk});

  Future<void> getParams();
}
