// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'compression.dart';
import 'evfs/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chunk_abs_offset`, `vault_export_write`, `vault_resize_grow_impl`, `vault_resize_shrink_impl`, `write_encrypted_chunk`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `vault_write_stream`

/// Create a new vault file at `path` with the given capacity.
///
/// The algorithm string must be "aes-256-gcm" or "chacha20-poly1305".
Future<VaultHandle> vaultCreate({
  required String path,
  required List<int> key,
  required String algorithm,
  required BigInt capacityBytes,
}) => RustLib.instance.api.crateApiEvfsVaultCreate(
  path: path,
  key: key,
  algorithm: algorithm,
  capacityBytes: capacityBytes,
);

/// Open an existing vault, running WAL recovery if needed.
Future<VaultHandle> vaultOpen({required String path, required List<int> key}) =>
    RustLib.instance.api.crateApiEvfsVaultOpen(path: path, key: key);

/// Write (or overwrite) a named segment.
///
/// Compression is transparent: pass a `CompressionConfig` to compress before
/// encryption. MIME-aware skip applies when the segment name has an
/// already-compressed extension.
Future<void> vaultWrite({
  required VaultHandle handle,
  required String name,
  required List<int> data,
  CompressionConfig? compression,
}) => RustLib.instance.api.crateApiEvfsVaultWrite(
  handle: handle,
  name: name,
  data: data,
  compression: compression,
);

/// Read a named segment. Handles both monolithic and streaming segments.
/// Decompression is automatic for monolithic segments.
Future<Uint8List> vaultRead({
  required VaultHandle handle,
  required String name,
}) => RustLib.instance.api.crateApiEvfsVaultRead(handle: handle, name: name);

/// Read a named segment sequentially through a stream. Decompression is automatic.
Future<void> vaultReadStream({
  required VaultHandle handle,
  required String name,
  required bool verifyChecksum,
  required RustStreamSink<Uint8List> sink,
  required RustStreamSink<double> onProgress,
}) => RustLib.instance.api.crateApiEvfsVaultReadStream(
  handle: handle,
  name: name,
  verifyChecksum: verifyChecksum,
  sink: sink,
  onProgress: onProgress,
);

/// Write a file into the vault as a streaming segment.
///
/// Reads `file_path` in 64KB chunks and encrypts each independently.
/// This is the FRB-callable wrapper around `vault_write_stream`.
Stream<double> vaultWriteFile({
  required VaultHandle handle,
  required String name,
  required String filePath,
}) => RustLib.instance.api.crateApiEvfsVaultWriteFile(
  handle: handle,
  name: name,
  filePath: filePath,
);

/// Delete a named segment. The region is secure-erased and returned to the
/// free list for reuse by future writes.
Future<void> vaultDelete({required VaultHandle handle, required String name}) =>
    RustLib.instance.api.crateApiEvfsVaultDelete(handle: handle, name: name);

/// Resize vault data region capacity.
///
/// - Grow: extend file, CSPRNG-fill new space, relocate shadow index + WAL
/// - Shrink: validate segments fit, relocate shadow + WAL, truncate file
/// - Returns VaultFull if shrink would lose data
Future<void> vaultResize({
  required VaultHandle handle,
  required BigInt newCapacity,
}) => RustLib.instance.api.crateApiEvfsVaultResize(
  handle: handle,
  newCapacity: newCapacity,
);

/// List all segment names in the vault.
Future<List<String>> vaultList({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiEvfsVaultList(handle: handle);

/// Get vault capacity info.
Future<VaultCapacityInfo> vaultCapacity({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiEvfsVaultCapacity(handle: handle);

/// Get vault health/diagnostics (read-only).
Future<VaultHealthInfo> vaultHealth({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiEvfsVaultHealth(handle: handle);

/// Defragment the vault: compact all segments toward the data region start,
/// coalesce free space into a single contiguous block at the end.
///
/// Each segment move is individually WAL-protected for crash safety.
/// Encrypted bytes are copied as-is (no re-encryption). The free tail
/// is secure-erased with CSPRNG after all moves complete.
Future<DefragResult> vaultDefragment({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiEvfsVaultDefragment(handle: handle);

/// Consumes old handle (keys invalidated after rename). Returns new handle with new keys.
Future<VaultHandle> vaultRotateKey({
  required VaultHandle handle,
  required List<int> newKey,
}) => RustLib.instance.api.crateApiEvfsVaultRotateKey(
  handle: handle,
  newKey: newKey,
);

/// Export all vault segments into a self-contained `.mvex` encrypted archive.
///
/// Each segment is decrypted from the vault, then re-encrypted under an
/// ephemeral export key with a random per-segment nonce. The export key is
/// AEAD-wrapped with the caller's `wrapping_key`.
///
/// The vault is not modified by this operation.
Future<void> vaultExport({
  required VaultHandle handle,
  required List<int> wrappingKey,
  required String exportPath,
}) => RustLib.instance.api.crateApiEvfsVaultExport(
  handle: handle,
  wrappingKey: wrappingKey,
  exportPath: exportPath,
);

/// Close the vault — checkpoint WAL, release lock, zeroize keys on drop.
Future<void> vaultClose({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiEvfsVaultClose(handle: handle);

/// Unwraps export key, creates new vault at dest_path, writes all segments under new_master_key.
Future<VaultHandle> vaultImport({
  required String archivePath,
  required List<int> wrappingKey,
  required String destPath,
  required List<int> newMasterKey,
  required String algorithm,
  required BigInt capacityBytes,
}) => RustLib.instance.api.crateApiEvfsVaultImport(
  archivePath: archivePath,
  wrappingKey: wrappingKey,
  destPath: destPath,
  newMasterKey: newMasterKey,
  algorithm: algorithm,
  capacityBytes: capacityBytes,
);
