// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'hashing.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_full`

Stream<double> streamHashFile({
  required HasherHandle hasher,
  required String filePath,
}) => RustLib.instance.api.crateApiStreamingStreamHashFile(
  hasher: hasher,
  filePath: filePath,
);
